### ISSUE TITLE
Landing Page - Hero Section - Illustration to Replace Stock Photo

### ISSUE THREAD

**Issue by iamjoshfrank** [revelry-foundation/Project-Riddell#75]
### High level direction
- Looking for illustrations that represent open source, working better together, community effort that helps our friends and love ones.
- Imagery that shows a wide array, of multiple voices within our community being shared/listened to versus focusing in one individual

### Tactical direction
- Individuals are from across the communities of Louisiana
- Diverse ethnicities and diverse genders
- Individuals look up, down, and or to the right and left as if they’re looking at each other
- Should have expressions of curiosity and interest

**Comment by iamjoshfrank** [comment]
@wavemanstudio here you go.

**Comment by jeremybrady** [comment]
@wavemanstudio 
Like the [matrix of these photos](http://selfresearch.org/), 
and I could see us representing a wide swath of the community, 
specifically the state of Louisiana as part of hero image for this site.

Would be nice to reflect that similarly for a hero illustration on this landing page.

CC @iamjoshfrank @CheetoMao @gerardramos for visibility

**Comment by iamjoshfrank** [comment]
@wavemanstudio - I moved this Issue into our `Implement` column with an indication you're currently working on this illustration. Our kanban for the Nightingale project is found here:

https://kanban.prod.revelry.net/app/revelry-foundation/nightingale

Feel free to hit "pause" if you're not actively working on this Issued.

**Comment by wavemanstudio** [comment]
@iamjoshfrank @jeremybrady - working on the grid of portraits, currently 8 columns by 4 rows of square portraits. Feeling like this is reasonable number I can finish EOD PST. But keeping it modular, so we can continue to expand on the dimensions if we find it necessary.

**Comment by wavemanstudio** [comment]
![Nightengale_LandingPortraits](https://user-images.githubusercontent.com/17013826/84202937-64eaa080-aa5d-11ea-88d7-c6e59fbf4bd5.jpg)
Here's the grid of portraits. We could sprinkle in the portraits from the other two illos if needed.
@jeremybrady @iamjoshfrank
